name: Unit tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  TERM: xterm-256color

on:
  pull_request:
    branches:
      - main
    paths:
      - 'tests/**'
      - 'share/**'
      - 'zinit*.zsh'
      - '.github/workflows/tests.yaml'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  zunit-tests:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['macos-latest','ubuntu-latest']
        test: ['annexes', 'gh-r', 'ices', 'plugins', 'snippets']
      fail-fast: false
    steps:
      - name: checkout ${{ github.repository }}
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: install homebrew
        id: setup-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      # - name: "install musl"
      #   if: runner.os == 'Linux'
      #   run: sudo apt-get install build-essential curl file gcc gcc-multilib glibc-source libc6 libc6-dev unzip xz-utils zsh

      - name: "install dependencies"
        id: install-deps
        run: |
          export HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1
          brew install --force --overwrite gnu-sed coreutils unzip xz zsh

      - name: "install zunit"
        id: install-zunit
        run: |
          mkdir -p "$HOME/.local/bin" && echo "$HOME/.local/bin" >> $GITHUB_PATH
          git clone --depth 1 https://github.com/zdharma-continuum/zunit; cd ./zunit
          zsh -c -l './build.zsh' && sudo chmod u+x ./zunit && cp ./zunit "$HOME/.local/bin/"

      - name: ${matrix.test}
        run: zunit run --fail-fas --verbose tests/${matrix.test}.zunit
